services:
  xmrig-proxy:
    image: ariizona/xmrig-proxy:latest
    build: .
    container_name: xmrig-proxy
    environment:
      - POOL=<your pool url>
      - USER=<your username or wallet here>
      - PASSWORD=<your password on pool>
      - ALGO=<needed mining algorithm>
    ports:
      - "3333:3333"
      - "3334:3334"
    restart: unless-stopped
