name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Get latest XMRig-Proxy release version
      id: get_latest_xmrig-proxy_release
      run: echo "tag=$(curl -sL https://api.github.com/repos/xmrig/xmrig-proxy/releases/latest | jq -r .tag_name)" >> $GITHUB_ENV
    - name: Build the Docker image
      id: build_docker_image
      run: docker build . --file Dockerfile --build-arg XMRIG_PROXY_VERSION=${{ env.tag }} --tag "ariizona/xmrig-proxy:${{ env.tag }}" --tag "ariizona/xmrig-proxy:latest"
    - name: Push the Docker image
      id: push_docker_image
      run: docker push --all-tags ariizona/xmrig-proxy

